# SPDX-License-Identifier: CC0-1.0
# Copyright (c) 2026 Christoph Böhm
# 
# This configuration is dedicated to the public domain under CC0-1.0.
# You may copy, modify, and use it for any purpose without permission.

title: COMET - Cost-efficient Open-Source Multicopter for Embedded-Systems Teaching 
description: Documentation